##### ME200, Johannes Ruf and Luitgard Veraart

# Day 1 -- First steps in Python

# This is a gonna be a very large headline

## This is a small headline

####  An even smaller headline

Just a check: 

In [2]:
import sys
print(sys.version)

3.8.5 (default, Sep  4 2020, 02:22:02) 
[Clang 10.0.0 ]


## Some info on Python

Python is a general-purpose programming language initially developed by Guido van Rossum in the 1990s. 

Python is a dynamic, interpreted (bytecode-compiled) language. This means we can type statements into the interpreter and they are executed immediately. In contrast, languages such as Java and C are compiled languages.

**Where does Python programming fit into your life?**

* Super small so shows up on embedded devices.
* Several libraries for building great web apps.
* Python popular at Disney and Lucas Film.
* Large community of users, easy to find help and documentation.
* Has a strong position in scientific computing. 
* Heavily used in science (CERN and NASA) with dedicated libraries to specific areas.

The real power of Python comes from sets of functions put together in *packages*. 

Here are some examples (all of them are very useful in finance):

- `math` : some mathematical functions 
- `numpy` : vector and matrix capabilities and operations
- `scipy` : numerical scientific computing including integration, fixed points, solving ODEs, optimisation, ...
- `matplotlibs` : plots
- `pandas` : database access and manipulation, and more plots routines

Here some more used in other fields:
* `earthpy` – earth sciences
* `astropy` – Astronomy
* `pygame` – writing video games; supports art, music, sound, video projects, mouse and keyboard interaction

## Jupyter notebooks

This is a Jupyter notebook. It is an interface allowing us to combine code (in this case Python) and formatted text in a unified way.

The basic unit in a notebook is a *cell*. You are right now reading the content of a "Markdown" cell, designed to input formatted text. There are also 'Code' cells, designed to input executable code. 

- You can **add** a new cell by clicking on the + button on the lower toolbar. Alternatively, press A (for inserting a cell above or B for inserting a cell below).
- Click on the cell to start **editing** it. Alternatively, you can move between cells with your arrows (note the blue highlighter on the right), and click **Enter** to edit one cell.
- To change the type of cell (from 'code' to 'markdown', use the choice tab on toolbar while on the cell.
- To run the code on a cell (or to format the text you input) you can either click on the 'play' button on the lower toolbar, or hit Ctrl+Enter
- You can also cut, paste and move cells. Hover your mouse over the buttons on the lower toolbar to know more. 

To familiarise yourself with the interface:
- On the upper toolbar, click on *Help> User Interface tour*, and follow the instructions to get an overview of this interface.
- For more information on the Python notebook in general, click on *Help> Notebook help*.
- To know more about the keyboard shortcuts, go to *Help> Keyboard shortcuts*.

## Basic expressions

Having briefly reviewed the interface, let us start our review of Python. We will introduce different commands and explain their use: please run the commands as we learned above, and understand their function. 

We start by saying hi....

In [3]:
print('Hello world')

Hello world


The operator *=*, with a single equal, is used to make an assignment:

In [4]:
message = 'hello again!!!'  # This is an assignment
print(message)

hello again!!!


Note in passing that we can make comments on a code cell by preceding the comment by *#*

## Some basic arithmetics

We can do some basic mathematics as follows:

In [5]:
3+4

7

In [6]:
3/9

0.3333333333333333

In [7]:
sqrt(2)

NameError: name 'sqrt' is not defined

Core Python doesn't have all functions. Almost always we need to import commands from libraries, i.e., tell Python where certain commands are stored.

In [9]:
from math import sqrt

In [10]:
sqrt(2)

1.4142135623730951

Alternatively, we could also execute the following two commands.

In [11]:
import math

In [12]:
math.sin(3)

0.1411200080598672

Division is a bit special. Observe the result of the following operations:

In [13]:
print(20/7)
print(20//7)

2.857142857142857
2


Indeed, the double slash */* signals integer division.

The *modulo* operator, that allow us to obtain the residual of a division, is also included:

In [14]:
20 % 7

6

Powers are defined using the operator double star '**'

In [15]:
print(2** - 1, 2**0, 2**1, 2**2)

0.5 1 2 4


## Vectors as `numpy` arrays

Let us now look at `numpy`. `numpy` is a scientific library that has been optimised to perform vector and matrix operations.

In [16]:
import numpy as np

This creates a vector:

In [17]:
v = np.array([5,3,-1, 0, 2])

In [18]:
print(v)

[ 5  3 -1  0  2]


Getting familiar with “vectorized thinking” is very important for using Python effectively.

To add up the entries of `v`, to get the largest and smallest value of `v`, and to get the length of `v` use the following:

In [19]:
v.sum()

9

In [20]:
v.max()

5

In [21]:
v.min()

-1

In [22]:
v.size     # no parentheses here!

5

Indexing in Python starts at zero! 

In [23]:
v[0]   # the first element

5

In [24]:
v[1]   # the second element

3

To get the array (0, 1, 2, ..., 10)

In [25]:
np.arange(11)    

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

More generally, if `m` and `n` are integers, then we get the vector (m, m+1, ..., n) as follows

In [26]:
m = 5
n = 11

np.arange(m, n + 1)

array([ 5,  6,  7,  8,  9, 10, 11])

Many operations in `numpy` arrays are interpreted componentwise:

In [27]:
print(v)
print(v**3)

[ 5  3 -1  0  2]
[125  27  -1   0   8]


In [28]:
a = np.array([2, 3, 0])
b = np.array([5, -1, 2])
a + b

array([7, 2, 2])

Since operations are mostly pointwise, the sizes of vectors need to coincide or an error will be delacred.

In [29]:
c = np.array([1, 2])

In [30]:
a + c

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

However, if Python can make sense of it then sizes of vectors etc do not have to agree (so called broadcasting):

In [31]:
a + 3

array([5, 6, 3])

## Binomial coefficients

Let's say we want to compute $\binom{8}{2}$ and other such quantities.

The following command from the `math` library gives us a solution.

In [32]:
math.comb(8, 2)

28

## Sampling and simulation

`numpy` has very useful functionality to sample randomly.

For example, the following samples randomly `k` without replacement from 0, 1, 2, ..., `n` (with equal probability):

In [33]:
n = 7
k = 4
np.random.choice(n, size=k, replace=False)

array([0, 2, 4, 1])

You’ll probably get something different when you try it!

With replacement, the following works:

In [34]:
np.random.choice(n, size=k, replace=True)

array([1, 6, 6, 1])

`np.random.choice` also allows to specify a vector of probabilities to be used to sample:

In [36]:
np.random.choice(5, size=3, p=[0.1, 0, 0.3, 0.6, 0], replace=True)

array([3, 2, 3])

The previous command samples 3 numbers between 0 and 4, with replacement, and with probabilities given by (0.1, 0, 0.3, 0.6, 0).

Generating many random samples will allow us to perform a simulation for probability problems.